application: nthonur
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.handler.application
  login: admin
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /static
  static_dir: public
- url: .*
  script: app.app

derived_file_type:
- python_precompiled

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^node_modules$
- ^\.vscode$

builtins:
- remote_api: on
- deferred: on
- appstats: on
